# Builder configuration for local testing with localhost registry

[[buildpacks]]
uri = "buildpack/"

[[order]]
[[order.group]]
id = "io.amazme.buildpacks.mlflow-model"
version = "0.1.0"

[build]
image = "localhost:5000/fedora-mlserver-build:43"

[[run.images]]
image = "localhost:5000/fedora-mlserver-run:43"
